image: maven:3.8.6-openjdk-11

stages:
    - build
    - test


maven-build-stage:
  stage: build
  script: mvn clean install -DskipTests
  only:
    - develop

maven-test-stage:
  stage: test
  script: mvn test -Dspring.profiles.active=test -Djasypt.encryptor.password=Ces!123
  only:
    - develop